apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyro-test
  labels:
    purpose: someCompanyBot
spec:
  selector:
    matchLabels:
      app: hyro-test
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: hyro-test
    spec:
      containers:
      - name: hyro-test
        image: hyroacr.azurecr.io/hyro-test:v2
        ports:
        - containerPort: 3000
---
kind: Service             #+
apiVersion: v1            #+
metadata:                 #+
  name: hyro-test-server  #+
spec:                     #+
  selector:               #+
    app: hyro-test        #+
  ports:                  #+
  - protocol: TCP         #+
    targetPort: 3000      #+
    port: 80              #+
    name: http            #+
  type: LoadBalancer      #+